routes:
  /: landing
  /es/suscribite/:
    template: suscribite
    data: page.suscribite
  /gracias/:
    template: gracias
    data: page.gracias
  /oh-yes/:
    template: oh-yes
    data: page.oh-yes
  /es/rutas/:
    template: rutas
    data: page.rutas
  /es/canon/:
    template: canon
    data: page.canon
  /es/revista-421/:
    template: revista
    data: page.revista-421
  /es/pitcheale-a-421/:
    template: pitcheale
    data: page.pitcheale-a-421
  /es/mi-suscripcion/:
    template: mi-suscripcion
    data: page.mi-suscripcion
  /en/my-subscription/:
    template: my-subscription
    data: page.my-subscription
  /en/routes/:
    template: routes
    data: page.routes
  /en/canon/:
    template: canon-en
    data: page.canon-en
  /es/ultimos-posts/:
    template: last-posts-es
    data: page.ultimos-posts
  /en/last-posts/:
    template: last-posts-en
    data: page.last-posts
  /en/subscribe/:
    template: subscribe
    data: page.subscribe

  /es/tag/cultura/:
    template: tag-cultura
    data: tag.cultura
  /es/tag/tecnologia/:
    template: tag-tecnologia
    data: tag.tecnologia
  /es/tag/juegos/:
    template: tag-juegos
    data: tag.juegos
  /es/tag/vida-real/:
    template: tag-vida-real
    data: tag.vida-real

  /es/tag/el-canon/:
    template: tag-el-canon
    data: tag.el-canon

  /es/tag/cannabis/:
    template: tag-secundario-cannabis
    data: tag.cannabis
  /es/tag/tutoriales/:
    template: tag-secundario-tutoriales
    data: tag.tutoriales
  /es/tag/argentina/:
    template: tag-secundario-argentina
    data: tag.argentina
  /es/tag/cripto/:
    template: tag-secundario-cripto
    data: tag.cripto
  /es/tag/deportes/:
    template: tag-secundario-deportes
    data: tag.deportes
  /es/tag/filosofia/:
    template: tag-secundario-filosofia
    data: tag.filosofia
  /es/tag/historieta/:
    template: tag-secundario-historieta
    data: tag.historieta
  /es/tag/internet/:
    template: tag-secundario-internet
    data: tag.internet
  /es/tag/libros/:
    template: tag-secundario-libros
    data: tag.libros
  /es/tag/magic-the-gathering/:
    template: tag-secundario-magicthegathering
    data: tag.magic-the-gathering
  /es/tag/memes/:
    template: tag-secundario-memes
    data: tag.memes
  /es/tag/musica/:
    template: tag-secundario-musica
    data: tag.musica
  /es/tag/peliculas/:
    template: tag-secundario-peliculas
    data: tag.peliculas
  /es/tag/series/:
    template: tag-secundario-series
    data: tag.series
  /es/tag/soberania/:
    template: tag-secundario-soberania
    data: tag.soberania
  /es/tag/videojuegos/:
    template: tag-secundario-videojuegos
    data: tag.videojuegos
  /es/tag/warhammer/:
    template: tag-secundario-warhammer
    data: tag.warhammer
  /es/tag/wiki/:
    template: tag-secundario-wiki
    data: tag.wiki

  /en/tag/culture/:
    template: tag-culture
    data: tag.culture
  /en/tag/tech/:
    template: tag-tech
    data: tag.tech
  /en/tag/games/:
    template: tag-games
    data: tag.games
  /en/tag/real-life/:
    template: tag-real-life
    data: tag.real-life

collections:
  /es/:
    permalink: /es/{slug}/
    template: index
    filter: 'tag:-hash-en'
  /en/:
    permalink: /en/{slug}/
    template: en
    filter: 'tag:hash-en'

taxonomies:
  author: /author/{slug}/
