routes:
  /: landing
  /es/suscribite/: suscribite
  /gracias/: gracias
  /oh-yes/: oh-yes
  /es/rutas/: rutas
  /es/canon/: canon
  /es/revista-421/: revista
  /es/pitcheale-a-421/: pitcheale
  /es/mi-suscripcion/: mi-suscripcion
  /en/my-subscription/: my-subscription
  /en/routes/: routes
  /en/canon/: canon-en
  /es/ultimos-posts/: last-posts-es
  /en/last-posts/: last-posts-en

  /es/tag/cultura/: tag-cultura
  /es/tag/tecnologia/: tag-tecnologia
  /es/tag/juegos/: tag-juegos
  /es/tag/vida-real/: tag-vida-real

  /es/tag/el-canon/: tag-el-canon

  /es/tag/cannabis/: tag-secundario-cannabis
  /es/tag/tutoriales/: tag-secundario-tutoriales
  /es/tag/argentina/: tag-secundario-argentina
  /es/tag/cripto/: tag-secundario-cripto
  /es/tag/deportes/: tag-secundario-deportes
  /es/tag/filosofia/: tag-secundario-filosofia
  /es/tag/historieta/: tag-secundario-historieta
  /es/tag/internet/: tag-secundario-internet
  /es/tag/libros/: tag-secundario-libros
  /es/tag/magic-the-gathering/: tag-secundario-magicthegathering
  /es/tag/memes/: tag-secundario-memes
  /es/tag/musica/: tag-secundario-musica
  /es/tag/peliculas/: tag-secundario-peliculas
  /es/tag/series/: tag-secundario-series
  /es/tag/soberania/: tag-secundario-soberania
  /es/tag/videojuegos/: tag-secundario-videojuegos
  /es/tag/warhammer/: tag-secundario-warhammer
  /es/tag/wiki/: tag-secundario-wiki

  /en/tag/culture/: tag-culture
  /en/tag/tech/: tag-tech
  /en/tag/games/: tag-games
  /en/tag/real-life/: tag-real-life
  /en/subscribe/: subscribe

collections:
  /es/:
    permalink: /es/{slug}/
    template: index
    filter: 'tag:-hash-en'
  /en/:
    permalink: /en/{slug}/
    template: en
    filter: 'tag:hash-en'

taxonomies:
  author: /author/{slug}/
